//
package igu;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Cursos;

public final class Matricula extends javax.swing.JFrame {
    private Login log;
    
    ArrayList<Cursos> listaCursos=new ArrayList<>();
    DefaultTableModel modelo= new DefaultTableModel();
  
    public Matricula() {
        initComponents();
        modelo= new DefaultTableModel();
        modelo.addColumn("Cursos");
        refrescarTabla();
    }
    public void setLog (Login log){
        this.log = log;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        scrMatematica = new javax.swing.JComboBox<>();
        scrHistoria = new javax.swing.JComboBox<>();
        scrCivica = new javax.swing.JComboBox<>();
        scrLiteratura = new javax.swing.JComboBox<>();
        scrCiencias = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMatricula = new javax.swing.JTable();
        btnMatricula = new javax.swing.JButton();
        btnRegresar1 = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnVolver_login = new javax.swing.JButton();
        btnMatematicas = new javax.swing.JButton();
        btnEliminar_fila = new javax.swing.JButton();
        btnEliminar_todo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 68, 68));
        jPanel1.setForeground(new java.awt.Color(0, 68, 68));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Matricula");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Elige los cursos que llevaras este ciclo:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cuando elijas tus cursos, dale click al botón matricula.");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("-Matemática:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("-Historia del Perú:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("-Literatura:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("-Civica:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("-Ciencias:");

        scrMatematica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Matematica| Prof. Raúl Hernandez  | A0504  | Lun y Mie  2:00pm a 4:00pm", "Matematica| Prof. Javier Paucar       | A0307  | Mar y Jue  2:00pm a 4:00pm", "Matematica| Prof. Amanda Ruiz      | B0603  | Lun y Mie  4:30pm a 6:30pm", "Matematica| Prof. Jose Romero      | C0504  | Mar y Jue  4:30pm a 6:30pm" }));
        scrMatematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrMatematicaActionPerformed(evt);
            }
        });

        scrHistoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Historia| Prof. Marisol Mercede | A0304  | Lun  10:00am a 1:00pm", "Historia| Prof. Carlos Alberto     | A0105  | Jue   9:00am a 11:00pm", "Historia| Prof. Luis Campos       | B0503  | Mie   1:00pm a 4:00pm", "Historia| Prof. Juan Lopez          | C0704  | Mar  5:00pm a 8:00pm" }));
        scrHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrHistoriaActionPerformed(evt);
            }
        });

        scrCivica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Civica| Prof. Carmela Calderon | B0102   | Lun 8:00pm a 9:00pm", "Civica| Prof. Percy Coronel       | A0804  | Mar 5:00pm a 6:00pm", "Civica| Prof. Antonio Lima       | B0709   | Sab 9:00am a 10:00am", "Civica| Prof. Solano Ventura    | C0502   | Vier 10:00am a 11:00am" }));
        scrCivica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrCivicaActionPerformed(evt);
            }
        });

        scrLiteratura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Literat| Prof. Mario de Valle    | A0107  | Mar y Sab  8:00am a 9:30am", "Literat| Prof. Sara Ordoñez     | C0405  | Lun y Vier  9:00am a 10:30am", "Literat| Prof. Mario Lopez       | A403    | Lun y Mar  10:30am a 11:30am", "Literat| Prof. Renato Arevalo  | C0202  | Mar y Mier  11:00am a 1:30pm" }));
        scrLiteratura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrLiteraturaActionPerformed(evt);
            }
        });

        scrCiencias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Ciencias| Prof. Victoria Dueñas  | D0405 | Mier 1:00pm a 3:00pm", "Ciencias| Prof. Oscar Orihuela   | B0305  | Jue 8:00am a 10:00am", "Ciencias| Prof. Hernan Rios       | B0107  | Jue 11:30am a 1:30pm", "Ciencias| Prof. Lidia Toscano     | A0804 | Jue 6:00pm a 8:00pm" }));
        scrCiencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrCienciasActionPerformed(evt);
            }
        });

        tblMatricula.setBackground(new java.awt.Color(0, 204, 204));
        tblMatricula.setForeground(new java.awt.Color(0, 0, 0));
        tblMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cursos"
            }
        ));
        jScrollPane3.setViewportView(tblMatricula);

        btnMatricula.setText("Matricularse");

        btnRegresar1.setText("Regresar");

        btnRegistrar.setBackground(new java.awt.Color(0, 153, 153));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Matricula");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnVolver_login.setBackground(new java.awt.Color(0, 153, 153));
        btnVolver_login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver_login.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver_login.setText("Volver");
        btnVolver_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver_loginActionPerformed(evt);
            }
        });

        btnMatematicas.setBackground(new java.awt.Color(0, 153, 153));
        btnMatematicas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMatematicas.setForeground(new java.awt.Color(255, 255, 255));
        btnMatematicas.setText("Agregar cursos");
        btnMatematicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatematicasActionPerformed(evt);
            }
        });

        btnEliminar_fila.setBackground(new java.awt.Color(0, 153, 153));
        btnEliminar_fila.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar_fila.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar_fila.setText("Eliminar fila");
        btnEliminar_fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar_filaActionPerformed(evt);
            }
        });

        btnEliminar_todo.setBackground(new java.awt.Color(0, 153, 153));
        btnEliminar_todo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar_todo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar_todo.setText("Eliminar todo");
        btnEliminar_todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar_todoActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnEliminar_fila)
                .addGap(45, 45, 45)
                .addComponent(btnMatematicas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnEliminar_todo)))
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(scrMatematica, 0, 1, Short.MAX_VALUE)
                                        .addComponent(scrHistoria, 0, 1, Short.MAX_VALUE)
                                        .addComponent(scrCiencias, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(scrCivica, 0, 1, Short.MAX_VALUE)
                                        .addComponent(scrLiteratura, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE))
                                    .addGap(25, 25, 25)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1)))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver_login, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrMatematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrLiteratura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrCivica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrCiencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar_todo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMatematicas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegresar1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(btnMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVolver_login, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void refrescarTabla(){
        
        for (Cursos curso : listaCursos){
            Object a[]=new Object[1];
            a[0]=curso.getMatematica();
                    
            modelo.addRow(a);
             a[0]=curso.getHistoria();
           
            modelo.addRow(a);
             a[0]=curso.getLiteratura();
           
            modelo.addRow(a);
             a[0]=curso.getCivica();
           
            modelo.addRow(a);
             a[0]=curso.getCiencias();
           
            modelo.addRow(a);
        }
        
    tblMatricula.setModel(modelo);
   }

    
    private void scrMatematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrMatematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scrMatematicaActionPerformed

    private void scrHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrHistoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scrHistoriaActionPerformed

    private void scrCivicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrCivicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scrCivicaActionPerformed

    private void scrLiteraturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrLiteraturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scrLiteraturaActionPerformed

    private void scrCienciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrCienciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scrCienciasActionPerformed

    private void btnMatematicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatematicasActionPerformed
           Cursos curso=new Cursos();
           curso.setMatematica(scrMatematica.getSelectedItem().toString());
           curso.setHistoria(scrHistoria.getSelectedItem().toString());
           curso.setLiteratura(scrLiteratura.getSelectedItem().toString());
           curso.setCivica(scrCivica.getSelectedItem().toString());
           curso.setCiencias(scrCiencias.getSelectedItem().toString());
           listaCursos.add(curso);
             refrescarTabla();
    }//GEN-LAST:event_btnMatematicasActionPerformed

    private void btnEliminar_filaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar_filaActionPerformed
        int fila=tblMatricula.getSelectedRow();
        if(fila>=0){
            modelo.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccionar Fila");
        }
    }//GEN-LAST:event_btnEliminar_filaActionPerformed

    private void btnEliminar_todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar_todoActionPerformed
        int fila=tblMatricula.getRowCount();
        for (int i =fila-1;i>=0;i--){
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_btnEliminar_todoActionPerformed

    private void btnVolver_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver_loginActionPerformed
        log.setMatri(this);
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolver_loginActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        JOptionPane.showMessageDialog(null, "MATRICULA COMPLETADA");
    }//GEN-LAST:event_btnRegistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar_fila;
    private javax.swing.JButton btnEliminar_todo;
    private javax.swing.JButton btnMatematicas;
    private javax.swing.JButton btnMatricula;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnVolver_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> scrCiencias;
    private javax.swing.JComboBox<String> scrCivica;
    private javax.swing.JComboBox<String> scrHistoria;
    private javax.swing.JComboBox<String> scrLiteratura;
    private javax.swing.JComboBox<String> scrMatematica;
    private javax.swing.JTable tblMatricula;
    // End of variables declaration//GEN-END:variables
}
